#!/bin/bash

echo "🚀 AI解梦应用 - 快速启动脚本"
echo "================================="

echo ""
echo "方案1: LocalTunnel (推荐 - 2分钟搞定)"
echo "1. 安装LocalTunnel:"
echo "   npm install -g localtunnel"
echo ""
echo "2. 新终端运行："
echo "   lt --port 3000"
echo ""
echo "3. 复制得到的URL (如: https://xxx.loca.lt)"
echo ""
echo "4. 设置环境变量："
echo "   export PUBLIC_URL=https://xxx.loca.lt"
echo ""
echo "5. 重启服务器："
echo "   node server.js"
echo ""

echo "方案2: Serveo (无需安装)"
echo "1. 新终端运行："
echo "   ssh -R 80:localhost:3000 serveo.net"
echo ""
echo "2. 复制得到的URL (如: https://xxx.serveo.net)"
echo ""
echo "3. 设置环境变量："
echo "   export PUBLIC_URL=https://xxx.serveo.net"
echo ""
echo "4. 重启服务器："
echo "   node server.js"
echo ""

echo "方案3: Railway云部署 (一劳永逸)"
echo "1. 访问: https://railway.app"
echo "2. 连接GitHub仓库"
echo "3. 部署并设置环境变量"
echo ""

echo "方案4: 继续使用轮询模式 (当前已启用)"
echo "- 无需任何配置"
echo "- 访问 http://localhost:3000 测试"
echo "- 可能需要手动刷新查看图像结果"
echo ""

echo "🎯 立即测试当前功能："
echo "打开浏览器访问: http://localhost:3000"
echo ""